version: "3.9"

services:
  fuwal:
    image: fullon/funod:${NODE_IMG_VER}
    container_name: flon_wal
    working_dir: /opt/flon
    entrypoint: ["./bin/run-wallet.sh", "."]
    volumes:
      - ${host}/:/opt/flon
      - ${host}/bin/.bashrc:/root/.bashrc
      - ${host}/bin-script:/root/bin
    env_file:
      - .env 
    dns:
      - 114.114.114.114
      - 8.8.8.8
networks:
  default:
    name: flon
    external: true
